#load @"d:\GitHub\FsChessPgn\FsChessPgn\Types.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Util.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Player.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\PieceType.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Piece.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Rank.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\File.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Square.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\GameResult.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Annotation.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Bitboard.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Direction.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Attacks.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\FEN.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Move.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Board.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\MoveGenerate.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\PgnWrite.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\pMove.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\MoveTextEntry.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Game.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\MoveUtil.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\RegParse.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\Games.fs"
#load @"d:\GitHub\FsChessPgn\FsChessPgn\PgnWriter.fs"
open FsChessPgn.Data
do
    fsi.AddPrinter<Brd>(Board.ToStr)
    fsi.AddPrinter<Move>(MoveUtil.Desc)
